package com.dbottillo.mtgsearchfree.util

interface TrackingManager {
    fun trackCard(setName: String, position: Int)
    fun trackPage(page: String?)
    fun trackImage(url: String?)
    fun trackShareApp()
    fun trackAboutLibrary(libraryLink: String?)
    fun trackPriceError(url: String?)
    fun trackImageError(image: String?)
    fun trackShareCard(cardName: String?)
    fun trackReleaseNote()
    fun trackSortCard(color: Boolean)
    fun trackDatabaseExport()
    fun trackDatabaseExportError(error: String)
    fun trackOpenRateApp()
    fun trackEditDeck()
    fun trackDeckExport()
    fun trackDeckExportError()
    fun trackAddCardToDeck()
    fun trackAddCardToDeck(quantity: String)
    fun trackRemoveCardFromDeck()
    fun trackRemoveAllCardsFromDeck()
    fun trackMoveOneCardFromDeck()
    fun trackMoveAllCardFromDeck()
    fun trackSearch(searchParams: String?)
    fun trackOpenFeedback()
    fun trackNewDeck(deck: String)
    fun trackDeleteDeck(name: String)
    fun trackAddPlayer()
    fun trackResetLifeCounter()
    fun trackLunchDice()
    fun trackChangePoisonSetting()
    fun trackHGLifeCounter()
    fun trackOpenCard(position: Int)
    fun trackSearchError(message: String?)
    fun trackDeleteWidget()
    fun trackAddWidget()
    fun trackEditPlayer()
    fun trackLifeCountChanged()
    fun trackPoisonCountChanged()
    fun trackScreenOn()
    fun trackRemovePlayer()
    fun logOnCreate(message: String)
}
